server:
  port: 9052
spring:
  application:
    name: task-service
feign:
  client:
    config:
      core-service:
        name: core-service
        url: http://localhost:9050/api/v1/core
        connectTimeout: 5000
        readTimeout: 5000
task:
  save-special-task:
    cron: '* * * * * *'